config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :addresses
  resources :brands
  resources :sizes
  resources :categories
  resources :comments
  resources :sellers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'items#index'
  resources :users, onry: [:index, :show, :edit] do
    collection do
      get 'confirmation'
      get 'credit'
    end
  end
  resources :signup, only: [:index, :create] do
    collection do
      get 'registration'
      get 'sms'
      get 'address'
      get 'creditcard'
      get 'complete'
    end
  end
  resources :items do
    collection do
      post 'purchase'
    end
  end

  resources :card, only: [:new, :show, :create] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase, only: [:index] do
    collection do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end
end

app/models/seller.rb
class Seller < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :set_seller, only: [:show, :edit, :update, :destroy]

  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = Seller.all
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show
  end

  # GET /sellers/new
  def new
    @seller = Seller.new
  end

  # GET /sellers/1/edit
  def edit
  end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(seller_params)

    respond_to do |format|
      if @seller.save
        format.html { redirect_to @seller, notice: 'Seller was successfully created.' }
        format.json { render :show, status: :created, location: @seller }
      else
        format.html { render :new }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/1
  # PATCH/PUT /sellers/1.json
  def update
    respond_to do |format|
      if @seller.update(seller_params)
        format.html { redirect_to @seller, notice: 'Seller was successfully updated.' }
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    @seller.destroy
    respond_to do |format|
      format.html { redirect_to sellers_url, notice: 'Seller was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller
      @seller = Seller.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seller_params
      params.fetch(:seller, {})
    end
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/_form.html.haml
= form_for(seller) do |f|
  - if seller.errors.any?
    #error_explanation
      %h2
        = pluralize(seller.errors.count, "error")
        prohibited this seller from being saved:
      %ul
        - seller.errors.full_messages.each do |message|
          %li= message
  .actions
    = f.submit

app/views/sellers/edit.html.haml
%h1 Editing Seller
= render 'form', seller: @seller
= link_to 'Show', @seller
|
= link_to 'Back', sellers_path

app/views/sellers/index.html.haml
%p#notice= notice
%h1 Sellers
%table
  %thead
    %tr
      %th{:colspan => "3"}
  %tbody
    - @sellers.each do |seller|
      %tr
        %td= link_to 'Show', seller
        %td= link_to 'Edit', edit_seller_path(seller)
        %td= link_to 'Destroy', seller, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Seller', new_seller_path

app/views/sellers/new.html.haml
.sell-container

  %header.signup-header
    %h1
      = link_to root_path do
        = image_tag 'fmarket_logo_red.svg'

  %main.sell-main
    %section.sell-main__container
      #sell-container
        %div
          .sell-main__inner
            %h2.sell-main__head
              商品の情報を入力
            = form_for @item, url: root_path, class:'sell-main__form' do |f|
              .sell-main__upload-box
                %h3.sell-main__upload-head
                  出品画像
                  %span.sell-main__form-require 必須
                %p 最大10枚までアップロードできます
                .sell-main__dropbox-container.clearfix.state-image-number-10
                  .sell-main__upload-items-container
                    .sell-main__upload-items.sell-main__upload-items--have-item-0{ id: 'sell-main__upload-items' }
                      %ul.clearfix{ id: 'output' }
                        = f.label :images, class: 'sell-main__upload-label', id: 'dropArea' do
                          .sell-main__upload-drop-box.sell-main__upload-drop-box--have-item-0{ id: 'sell-main__upload-drop-box' }
                            = f.file_field :images, multiple: true, class: 'sell-main__upload-drop-file', style: 'display: none;'
                            %pre.sell-main__visible-pc
                              ドラッグアンドドロップ
                              またはクリックしてファイルをアップロード
                            %i.fas.fa-camera         
                    
              .sell-main__content
                .sell-main__form-group
                  = f.label '商品名', class: 'sell-main__label'
                  %span.sell-main__form-require 必須
                  = f.text_field :name, class: 'sell-main__input-default', placeholder: '商品名（必須 40文字まで)'
                  
                .sell-main__form-group
                  = f.label '商品の説明', class: 'sell-main__label'
                  %span.sell-main__form-require 必須
                  = f.text_area :content, class: 'sell-main__textarea-default', placeholder: '商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。', rows: '5' 
                  
              .sell-main__content.clearfix
                %h3.sell-main__sub-head 商品の詳細
                .sell-main__form-box{ id: 'sell-main__form-box--detail' }
                  .sell-main__form-group
                    = f.label :category_id do
                      商品カテゴリー
                      %span.sell-main__form-require 必須
                    %div{ id: 'sell-main__select-category--wrapper' }
                      .sell-main__select-wrap
                        %i.fas.fa-chevron-down
                        = f.collection_select :seller, Category.where(sub: '0'), :id, :name, { prompt: '--' }, class: 'sell-main__select-default', id: 'sell-main__select-category--main'
                    
                  .sell-main__form-group
                    = f.label :condition do
                      商品の状態
                      %span.sell-main__form-require 必須
                    .sell-main__select-wrap
                      %i.fas.fa-chevron-down
                      = f.collection_select :status, Condition.all, :id, :value, { prompt: '--' }, class: 'sell-main__select-default'
          
              
                
                  .sell-main__form-group{ id: 'sell-main__form-group--delivery-charge'}
                    = f.label :delivery_charge_id do
                      配送料の負担
                      %span.sell-main__form-require 必須
                    .sell-main__select-wrap
                      %i.fas.fa-chevron-down
                      = f.collection_select :cost_payer, DeliveryCharge.all, :id, :value, { prompt: '--' }, class: 'sell-main__select-default'
            
                  .sell-main__form-group
                    = f.label :delivery_area_id do
                      発送元の地域
                      %span.sell-main__form-require 必須
                    .sell-main__select-wrap
                      %i.fas.fa-chevron-down
                      = f.collection_select :prefecture_code, Prefecture.all, :id, :name, { prompt: '--' }, class: 'sell-main__select-default'
                
                  .sell-main__form-group
                    = f.label :delivery_days do
                      発送までの日数
                      %span.sell-main__form-require 必須
                    .sell-main__select-wrap
                      %i.fas.fa-chevron-down
                      -# = f.collection_select :days, DeliveryDays.all, :id, :value, { prompt: '--' }, class: 'sell-main__select-default'
          
              .sell-main__content.clearfix
                
                .sell-main__form-box
                  %ul.sell-main__price
                    %li.sell-main__form-group
                      .clearfix
                        = f.label :price, class: 'sell-main__left' do
                          価格(300~)円
                          %span.sell-main__form-require 必須
                        .sell-main__right.sell-main__price-input 
                          
                        %div
                          = f.text_field :name, { class: 'sell-main__input-default',id: 'sell-main__price-input', placeholder: '例）300',  value: '' }
          

                    %li.clearfix
                      .sell-main__left
                        販売手数料 (10%)
                      .sell-main__right{ id: 'sell-main__fee' } -
                    %li.clearfix.bold
                      .sell-main__left 販売利益
                      .sell-main__right{ id: 'sell-main__profit' } -
              .sell-main__modal{ role: 'dialog', abindex: '-1' }
                .sell-main__modal-inner
              .sell-main__content.sell-main__btn-box
                
                = f.submit '出品する', class: 'sell-main__btn-default sell-main__btn-red'
                = link_to root_path, class: 'sell-main__btn-default sell-main__btn-gray' do
                  もどる

  .signup-footer
    %nav
      %ul.clearfix
        %li
          = link_to root_path do
            プライバシーポリシー
        %li
          = link_to root_path do
            メルカリ利用規約
        %li
          = link_to root_path do
            特定商取引に関する表記
    = link_to root_path, class: 'signup-footer__logo' do
      = image_tag 'fmarket_logo_white.svg', alt: 'mercari', height: '65', width: '80'
    %p
      %small
        © 2019 Mercari   
          

          

app/views/sellers/show.html.haml
.item__details
 %h2.item-name.bold
  ジャケット
 .item__details__main-content
  .item__details__main-content-boxes
   .item__details__main-content-boxes__subject.back-silver
    .sold-item-big
     .sold-item--text-big SOLD
     = image_tag 'gahag-005749.jpg'
    .photos
     .photos--small
      -# - @item.images.each do |image|サーバーサイド未完成のためコメントアウト
       %img.sub{src: image.image}/

   %table.item-detail-table
    %tr
     %th.back-silver 出品者
     %td
      高橋
      .user-rating
       .item-user-ratings
       %i.fas.fa-laugh
        %span 100
       .item-user-ratings
       %i.fas.fa-meh
       %span 0
       .item-user-ratings
       %i.fas.fa-frown
       %span 0
    %tr
     %th.back-silver カテゴリー
     %td
      .item-detail-table-sub-category
      %i.fa.fa-chevron-right.items-link_to
      = link_to "ジャケット/アウター", class: "items-link_to"
      .item-detail-table-sub-sub-category
      %i.fa.fa-chevron-right.items-link_to
      = link_to "ダウンジャケット", class: "items-link_to"
    %tr
     %th.back-silver ブランド
     %td
      -# = link_to @item.brand.name, class: "items-link_to"サーバーサイド未完成のためコメントアウト
      ck
    %tr
     %th.back-silver 商品のサイズ
     %td
      -# = @item.size.sizeサーバーサイド未完成のためコメントアウト
      L
    %tr
     %th.back-silver 商品の状態
     %td
      -# = @item.condition.conditionサーバーサイド未完成のためコメントアウト
      汚れ、破れなし。
    %tr
     %th.back-silver 配送料の負担
     %td
      -# = @item.postage.burdenサーバーサイド未完成のためコメントアウト
      送料こみ（出品者負担）
    %tr
     %th.back-silver 配送の方法
     %td
      -# = @item.delivery_method.methodサーバーサイド未完成のためコメントアウト
      ゆゆメルカリ便
    %tr
     %th.back-silver 発送元地域
     %td
      -# = link_to @item.prefecture.prefecture, class: "items-link_to"サーバーサイド未完成のためコメントアウト
      ケアンズ（オーストラリア）
    %tr
     %th.back-silver 発送日の目安
     %td
      -# = @item.delivery_day.dayサーバーサイド未完成のためコメントアウト
      一ヶ月以内に発送
 .item-price-box
  %span.item-price.bold $150
  -#  = converting_to_jpy(@item.price)サーバーサイド未完成のためコメントアウト
  %span.item-tax (税込)
  %span.item-shipping-fee 送料込み
  -# - if @item.item_state_id == 3サーバーサイド未完成のためコメントアウト
   = link_to "売り切れました", root_path, class: "buy-btn status-gray",method: :get
  -# - elsif user_signed_in? && (@item.user_id != current_user.id) && @item.item_state_id == 1サーバーサイド未完成のためコメントアウト
   = link_to "購入画面へ進む", "/transaction/buy/#{@item.id}", class: "buy-btn, status-red",method: :get
  -# - unless user_signed_in? || @item.item_state_id == 3サーバーサイド未完成のためコメントアウト
   = link_to "購入画面へ進む", user_session_path, class: "buy-btn, status-red", method: :get

 .item-description
  %p.item-description-inner
  -#  = @item.descriptionサーバーサイド未完成のためコメントアウト
.item-edit__box
 .item-edit__box-main
 - if user_signed_in? 
  .item-edit__box__price.back-red.font-white
   = link_to "商品の編集", "#", method: :get
  .item-edit__box__or or
  .item-edit__box__main-contents
   = form_tag("#", method: :post, action: :stop) do
    %button:type: "submit", class: "submit"}
    %span.font-white 出品を停止する
  .item-edit__box__main-contents__button
   %button{type: "submit", class: "submit", id: "openModal"}
   %span.font-white この商品を削除する

 - else
  .item-button-container
   .item-button-container__left
    %button{name: "like", type: "button"}
     %i.far.fa-heart
     %span いいね！
     %span
      -# = @item.likes_countサーバーサイド未完成のためコメントアウト
    %button{name: "report", type: "button"}
     %i.far.fa-flag
     %span 不適切な商品の報告
   .item-button__right.items-link_to
    -# = fa_icon "lock"サーバーサイド未完成のためコメントアウト
    = link_to '購入画面に進む', purchase_index_path, class: 'itembuy-price-box', id: 'itembuy-price-box__decoration'


  .item-edit__box__main-contents__message
  .message-content__box

.message-content__box
 .message-content__box__form
  %form.message-form{method: "post"}
  %input{type: "hidden"}
  %p.attention 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
  %input{type: "hidden"}
  %input{type: "hidden"}
  %textarea.text{type: "text", name: "body"}
  .message-sumit__details
   %button{type: "submit", class: "submit"}
    %span.font-white コメントする
.next_or_back
 .previous-product.items-link_to
  -# =fa_icon "#"サーバーサイド未完成のためコメントアウト
  = link_to "前の商品へ", "#"
 .next-product.items-link_to
  = link_to "次の商品へ", "#"
  -# = fa_icon "#"サーバーサイド未完成のためコメントアウト

.item-snsbox
 .sns
  .facebook
   %i.fab.fa-facebook-square
  .twitter
   %i.fab.fa-twitter-square
  .pinterest
   %i.fab.fa-pinterest-square