config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :addresses
  resources :brands
  resources :sizes
  resources :categories
  resources :comments
  resources :sellers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'items#index'
  resources :users, onry: [:index, :show, :edit] do
    collection do
      get 'confirmation'
      get 'credit'
    end
  end
  resources :signup, only: [:index, :create] do
    collection do
      get 'registration'
      get 'sms'
      get 'address'
      get 'creditcard'
      get 'complete'
    end
  end
  resources :items do
    collection do
      post 'purchase'
    end
  end

  resources :card, only: [:new, :show, :create] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase, only: [:index] do
    collection do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :sellers, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :item_images, dependent: :destroy
  has_many :users, through: :sellers
  has_many :cards
  # belongs_to :size_type
  accepts_nested_attributes_for :item_images, allow_destroy: true
  # belongs_to :user
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  # require 'payjp'
  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    # 出品機能未実装のため仮置き
    @user = User.find(@item.user_id)
    @prefecture = Prefecture.find(@item.prefecture_code)
    @category = Category.find(@item.category_id)
    @delivery_charge = DeliveryCharge.find(@item.delivery_charge)
    @delivery_days= DeliveryDay.find(@item.delivery_days)
    @condition = Condition.find(@item.condition_id)
  end

  # GET /items/new
  def new
    @item = Item.new
    @item.item_images.build
    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create

    @item = Item.new(item_params)
    #まだView設定がまだのため仮の登録データ、あとでViewからのデータをitem_paramsで定義します。
    atai = 1
    watasi = "hoge"

    @item.status = atai
    @item.upper_category = watasi
    @item.middle_category = watasi
    @item.lower_category = watasi
    @item.seller = watasi
    @item.size_type = watasi
    
    
    @item.save
    redirect_to root_path
    # respond_to do |format|
    #   if @item.save
    #     format.html { redirect_to @item, notice: 'Item was successfully created.' }
    #     format.json { render :show, status: :created, location: @item }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @item.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    if @item.update(item_params)
    redirect_to action: "index"
    else
    redirect_to action: "edit"
    end
  end
    

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
   @item.destroy
   redirect_to root_path
  end

  def purchase
    Payjp.api_key = Rails.application.secrets.PAYJP_SECRET_KEY
    Payjp::Charge.create(
      amount: 809, # 決済する値段
      card: params['payjp-token'], # フォームを送信すると作成・送信されてくるトークン
      currency: 'jpy'
    )
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      # 出品機能未実装のため仮置き
        @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      #params.require(:item).permit( :name, :content, :price, :prefecture_code, :status, :size_type, :seller, :created_at, :updated_at, :category_id, :condition_id,  :delivery_charge, :delivery_days　)#.merge(user_id: current_user.id)
      params.require(:item).permit(:name,:content,:category_id,:condition_id,:delivery_charge,:prefecture_code,:delivery_days,:price,item_images_attributes: [:image]).merge(user_id: current_user.id)
      
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= form_for(item) do |f|
  - if item.errors.any?
    #error_explanation
      %h2
        = pluralize(item.errors.count, "error")
        prohibited this item from being saved:
      %ul
        - item.errors.full_messages.each do |message|
          %li= message
  .actions
    = f.submit

app/views/items/edit.html.haml
.sell-container

  %header.signup-header
    %h1
      = link_to root_path do
        = image_tag 'fmarket_logo_red.svg'

  %main.sell-main
    %section.sell-main__container
      #sell-container
        %div
          .sell-main__inner
            %h2.sell-main__head 商品の情報を入力
            = form_for @item, class:'sell-main__form' do |f|
              .sell-main__upload-box
                %h3.sell-main__upload-head
                  出品画像
                  %span.sell-main__form-require 必須
                %p 最大10枚までアップロードできます
                .sell-main__dropbox-container.clearfix.state-image-number-10         
                  .sell-main__upload-items-container
                    .sell-main__upload-items.sell-main__upload-items--have-item-0{ id: 'sell-main__upload-items' }
                      %ul.clearfix{ id: 'output' }
                        
                        = f.fields_for :item_images do |image|
                          = image.label :image, class: 'sell-main__upload-label', id: 'dropArea' do
                            .sell-main__upload-drop-box.sell-main__upload-drop-box--have-item-0{ id: 'sell-main__upload-drop-box' }
                              = image.file_field :image, class: 'sell-main__upload-drop-file'
                            %pre.sell-main__visible-pc
                              ドラッグアンドドロップ
                              またはクリックしてファイルをアップロード
                            //%i.fas.fa-camera 

              .sell-main__content
                .sell-main__form-group
                  = f.label '商品名', class: 'sell-main__label'
                  %span.sell-main__form-require 必須
                  = f.text_field :name, class: 'sell-main__input-default', placeholder: '商品名（必須 40文字まで)'
                  
                .sell-main__form-group
                  = f.label '商品の説明', class: 'sell-main__label'
                  %span.sell-main__form-require 必須
                  = f.text_area :content, class: 'sell-main__textarea-default', placeholder: '商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。', rows: '5' 
                  
              .sell-main__content.clearfix
                %h3.sell-main__sub-head 商品の詳細
                .sell-main__form-box{ id: 'sell-main__form-box--detail' }
                  .sell-main__form-group
                    = f.label :category_id do
                      商品カテゴリー
                      %span.sell-main__form-require 必須
                    %div{ id: 'sell-main__select-category--wrapper' }
                      .sell-main__select-wrap
                        %i.fas.fa-chevron-down
                        = f.collection_select :category_id, Category.where(sub: '0'), :id, :name, { prompt: '--' }, class: 'sell-main__select-default', id: 'sell-main__select-category--main'
                    
                  .sell-main__form-group
                    = f.label :condition do
                      商品の状態
                      %span.sell-main__form-require 必須
                    .sell-main__select-wrap
                      %i.fas.fa-chevron-down
                      = f.collection_select :condition_id, Condition.all, :id, :value, { prompt: '--' }, class: 'sell-main__select-default'
          
              
                
                  .sell-main__form-group{ id: 'sell-main__form-group--delivery-charge'}
                    = f.label :delivery_charge_id do
                      配送料の負担
                      %span.sell-main__form-require 必須
                    .sell-main__select-wrap
                      %i.fas.fa-chevron-down
                      = f.collection_select :delivery_charge, DeliveryCharge.all, :id, :value, { prompt: '--' }, class: 'sell-main__select-default'
            
                  .sell-main__form-group
                    = f.label :delivery_area_id do
                      発送元の地域
                      %span.sell-main__form-require 必須
                    .sell-main__select-wrap
                      %i.fas.fa-chevron-down
                      = f.collection_select :prefecture_code, Prefecture.all, :id, :name, { prompt: '--' }, class: 'sell-main__select-default'
                
                  .sell-main__form-group
                    = f.label :delivery_days do
                      発送までの日数
                      %span.sell-main__form-require 必須
                    .sell-main__select-wrap
                      %i.fas.fa-chevron-down
                      = f.collection_select :delivery_days, DeliveryDay.all, :id, :value, { prompt: '--' }, class: 'sell-main__select-default'
          
              .sell-main__content.clearfix
                
                .sell-main__form-box
                  %ul.sell-main__price
                    %li.sell-main__form-group
                      .clearfix
                        = f.label :price, class: 'sell-main__left' do
                          価格(300~)円
                          %span.sell-main__form-require 必須
                        .sell-main__right.sell-main__price-input 
                          
                        %div
                          = f.text_field :price, { class: 'sell-main__input-default',id: 'sell-main__price-input', placeholder: '例）300' }
          

                    %li.clearfix
                      .sell-main__left
                        販売手数料 (10%)
                      .sell-main__right{ id: 'sell-main__fee' } -
                    %li.clearfix.bold
                      .sell-main__left 販売利益
                      .sell-main__right{ id: 'sell-main__profit' } -
              .sell-main__modal{ role: 'dialog', abindex: '-1' }
                .sell-main__modal-inner
              .sell-main__content.sell-main__btn-box
                
                = f.submit '変更する', class: 'sell-main__btn-default sell-main__btn-red'
                = link_to root_path, class: 'sell-main__btn-default sell-main__btn-gray' do
                  キャンセル

  .signup-footer
    %nav
      %ul.clearfix
        %li
          = link_to root_path do
            プライバシーポリシー
        %li
          = link_to root_path do
            メルカリ利用規約
        %li
          = link_to root_path do
            特定商取引に関する表記
    = link_to root_path, class: 'signup-footer__logo' do
      = image_tag 'fmarket_logo_white.svg', alt: 'mercari', height: '65', width: '80'
    %p
      %small
        © 2019 Mercari   
          

app/views/items/index.html.haml
%header
  .headernav
    .main
      .main__content
        .main__logo
          = link_to image_tag( "fmarket_logo_white.svg" ), '#'
        %form.form__action__search{action: "#"}
          %input{name: "keyword", placeholder: "何かお探しですか？", type: "search", value: "", class: "form__text"}
            %input{class: "sbtn", type: "submit", value: "検索"}
    .main__category
      - if user_signed_in?
        %ul.search-menu__show
          %li.search-menu__show__list.category
            %h3.show__category
              = link_to do
                %i.fas.fa-list-ul
                カテゴリーから探す
          %li.search-menu__show__list.brand
            %h3.show__brand
              = link_to '#', class: 'search-menu__show__list__text' do
                %i.fas.fa-tag
                ブランドから探す
        .main__menu__show
          = link_to user_path(current_user), class: 'main__menu__show__btn' do
            マイページ
      - else      
        %ul.search-menu
          %li.search-menu__list.category
            %h3.category
              = link_to '#', class: 'earch-menu__list__text' do
                %i.fas.fa-list-ul
                カテゴリーから探す
          %li.search-menu__list.brand
            %h3.brand
              = link_to '#', class: 'search-menu__list__text' do
                %i.fas.fa-tag
                ブランドから探す
        .main__menu
          = link_to new_user_registration_path, class: 'main__menu__new' do
            新規会員登録
          = link_to new_user_session_path, class: 'main__menu__login' do
            ログイン

.main
  .BBody  
    .Body
      #stage
        %input#back2{checked: "checked", name: "gal", type: "radio"}/
        %input#back3{name: "gal", type: "radio"}/
        %input#back4{name: "gal", type: "radio"}/
        %input#back5{name: "gal", type: "radio"}/
        %input#next1{name: "gal", type: "radio"}/
        %input#next2{name: "gal", type: "radio"}/
        %input#next3{name: "gal", type: "radio"}/
        %input#next4{name: "gal", type: "radio"}/
        #b_btn
          %label{for: "back2"}
            #left2.cover_left
              %span ＜
          %label{for: "back3"}
            #left3.cover_left
              %span ＜
          %label{for: "back4"}
            #left4.cover_left
              %span ＜
          %label{for: "back5"}
            #left5.cover_left
              %span ＜
        #n_btn
          %label{for: "next1"}
            #right1.cover_right
              %span ＞
          %label{for: "next2"}
            #right2.cover_right
              %span ＞
          %label{for: "next3"}
            #right3.cover_right
              %span ＞
          %label{for: "next4"}
            #right4.cover_right
              %span ＞
        #photos
          #photo1
          = image_tag "25926_1.jpg", size:"600x300"
          #photo2
          = image_tag "crop004ELFA191116.jpg", size:"600x300"
          -# #photo3
          -# = image_tag
          -# #photo4
          -# = image_tag
          -# #photo5
          -# = image_tag
          
      .Body__main
        .Body-category
          %h2.style_heading__3qSF6.common_fontFamily__3-3Si.style_responsiveLv1__3ygH4.sc-gmeYpB.vlRns 人気のカテゴリー
          .Body-category__title
            %ul.sc-RcBXQ.jzXryh
              %li.sc-iSDuPN.eltcJe
                %a.sc-fZwumE.sc-fQejPQ.UkWLD レディース
            
              %li.sc-iSDuPN.eltcJe
                %a.sc-fZwumE.sc-fQejPQ.UkWLD メンズ
              
              %li.sc-iSDuPN.eltcJe
                %a.sc-fZwumE.sc-fQejPQ.UkWLD 家電・スマホ・カメラ
              
              %li.sc-iSDuPN.eltcJe
                %a.sc-fZwumE.sc-fQejPQ.UkWLD おもちゃ・ホビー・グッズ
              
          %section.pickup
            %h1.pickup__head.bold 新着アイテム
            = link_to '#', class:'pickup__morelook' do
              もっと見る＞
            %section.pickup__area
              .pickup__area__text-center
              - @items.each do |item|
                .pickup__area__items-box__items
                  = link_to item_path(item.id) do
                    .pickup__area__items-box__items__photo
                      = image_tag item.item_images.first.image ,alt: "商品画像"
                    .pickup__area__items-box__items__body
                      %h4.pickup__area__items-box__items__name
                        = item.name
                      .pickup__area__items-box__items__num
                        .pickup__area__items-box__items__num__price.bold
                          ¥#{item.price}
                  %p.pickup__area__items-box__items__tax (税込)

        .Body__bland
          %h2.style_heading__3qSF6.common_fontFamily__3-3Si.style_responsiveLv1__3ygH4.sc-gmeYpB.vlRns 人気のブランド
          .Body__bland__title
            %ul.sc-RcBXQ.jzXryh
              %li.sc-iSDuPN.eltcJe
                %a.sc-fZwumE.sc-fQejPQ.UkWLD シャネン
              %li.sc-iSDuPN.eltcJe
                %a.sc-fZwumE.sc-fQejPQ.UkWLD ルイヴィ
              %li.sc-iSDuPN.eltcJe
                %a.sc-fZwumE.sc-fQejPQ.UkWLD シュプリーン
              %li.sc-iSDuPN.eltcJe
                %a.sc-fZwumE.sc-fQejPQ.UkWLD ナイス

          %section.pickup
            %h1.pickup__head.bold ブランド一覧
            = link_to '#', class:'pickup__morelook' do
              もっと見る＞
            %section.pickup__area
              .pickup__area__text-center
              - @items.each do |item|
                .pickup__area__items-box__items
                  = link_to item_path(@items) do
                    .pickup__area__items-box__items__photo
                      = image_tag item.item_images.first.image ,alt: "商品画像"
                    .pickup__area__items-box__items__body
                      %h4.pickup__area__items-box__items__name
                        = item.name
                      .pickup__area__items-box__items__num
                        .pickup__area__items-box__items__num__price.bold
                          ¥#{item.price}
                  %p.pickup__area__items-box__items__tax (税込)

    .Botan
      = link_to new_item_path , class: 'Botan__main' do
        .Botan__content
          .Botan__name 出品
          %svg.Botan__camera{"aria-hidden" => "true", :height => "16", :viewbox => "0 0 18 16", :width => "18"}
            %path{:d => "M6.3 0L4.653 1.778H1.8c-.99 0-1.8.8-1.8 1.778v10.666C0 15.2.81 16 1.8 16h14.4c.99 0 1.8-.8 1.8-1.778V3.556c0-.978-.81-1.778-1.8-1.778h-2.853L11.7 0H6.3zM9 13.333c-2.484 0-4.5-1.99-4.5-4.444 0-2.453 2.016-4.445 4.5-4.445s4.5 1.992 4.5 4.445c0 2.453-2.016 4.444-4.5 4.444zm0-1.6c1.59 0 2.88-1.273 2.88-2.844S10.59 6.044 9 6.044c-1.59 0-2.88 1.274-2.88 2.845 0 1.57 1.29 2.844 2.88 2.844z", :fill => "currentColor", "fill-rule" => "nonzero"}
= render 'shared/fakefooter'
= render 'shared/footer'

app/views/items/new.html.haml
.sell-container

  %header.signup-header
    %h1
      = link_to root_path do
        = image_tag 'fmarket_logo_red.svg'

  %main.sell-main
    %section.sell-main__container
      #sell-container
        %div
          .sell-main__inner
            %h2.sell-main__head 商品の情報を入力
            = form_for @item, class:'sell-main__form' do |f|
              .sell-main__upload-box
                %h3.sell-main__upload-head
                  出品画像
                  %span.sell-main__form-require 必須
                %p 最大10枚までアップロードできます
                .sell-main__dropbox-container.clearfix.state-image-number-10         
                  .sell-main__upload-items-container
                    .sell-main__upload-items.sell-main__upload-items--have-item-0{ id: 'sell-main__upload-items' }
                      %ul.clearfix{ id: 'output' }
                        = f.fields_for :item_images do |image|
                          = image.label :image, class: 'sell-main__upload-label', id: 'dropArea' do
                            .sell-main__upload-drop-box.sell-main__upload-drop-box--have-item-0{ id: 'sell-main__upload-drop-box' }
                              = image.file_field :image, class: 'sell-main__upload-drop-file'
                            %pre.sell-main__visible-pc
                              ドラッグアンドドロップ
                              またはクリックしてファイルをアップロード
                            //%i.fas.fa-camera 

              .sell-main__content
                .sell-main__form-group
                  = f.label '商品名', class: 'sell-main__label'
                  %span.sell-main__form-require 必須
                  = f.text_field :name, class: 'sell-main__input-default', placeholder: '商品名（必須 40文字まで)'
                  
                .sell-main__form-group
                  = f.label '商品の説明', class: 'sell-main__label'
                  %span.sell-main__form-require 必須
                  = f.text_area :content, class: 'sell-main__textarea-default', placeholder: '商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。', rows: '5' 
                  
              .sell-main__content.clearfix
                %h3.sell-main__sub-head 商品の詳細
                .sell-main__form-box{ id: 'sell-main__form-box--detail' }
                  .sell-main__form-group
                    = f.label :category_id do
                      商品カテゴリー
                      %span.sell-main__form-require 必須
                    %div{ id: 'sell-main__select-category--wrapper' }
                      .sell-main__select-wrap
                        %i.fas.fa-chevron-down
                        = f.collection_select :category_id, Category.where(sub: '0'), :id, :name, { prompt: '--' }, class: 'sell-main__select-default', id: 'sell-main__select-category--main'
                    
                  .sell-main__form-group
                    = f.label :condition do
                      商品の状態
                      %span.sell-main__form-require 必須
                    .sell-main__select-wrap
                      %i.fas.fa-chevron-down
                      = f.collection_select :condition_id, Condition.all, :id, :value, { prompt: '--' }, class: 'sell-main__select-default'
          
              
                
                  .sell-main__form-group{ id: 'sell-main__form-group--delivery-charge'}
                    = f.label :delivery_charge_id do
                      配送料の負担
                      %span.sell-main__form-require 必須
                    .sell-main__select-wrap
                      %i.fas.fa-chevron-down
                      = f.collection_select :delivery_charge, DeliveryCharge.all, :id, :value, { prompt: '--' }, class: 'sell-main__select-default'
            
                  .sell-main__form-group
                    = f.label :delivery_area_id do
                      発送元の地域
                      %span.sell-main__form-require 必須
                    .sell-main__select-wrap
                      %i.fas.fa-chevron-down
                      = f.collection_select :prefecture_code, Prefecture.all, :id, :name, { prompt: '--' }, class: 'sell-main__select-default'
                
                  .sell-main__form-group
                    = f.label :delivery_days do
                      発送までの日数
                      %span.sell-main__form-require 必須
                    .sell-main__select-wrap
                      %i.fas.fa-chevron-down
                      = f.collection_select :delivery_days, DeliveryDay.all, :id, :value, { prompt: '--' }, class: 'sell-main__select-default'
          
              .sell-main__content.clearfix
                
                .sell-main__form-box
                  %ul.sell-main__price
                    %li.sell-main__form-group
                      .clearfix
                        = f.label :price, class: 'sell-main__left' do
                          価格(300~)円
                          %span.sell-main__form-require 必須
                        .sell-main__right.sell-main__price-input 
                          
                        %div
                          = f.text_field :price, { class: 'sell-main__input-default',id: 'sell-main__price-input', placeholder: '例）300' }
          

                    %li.clearfix
                      .sell-main__left
                        販売手数料 (10%)
                      .sell-main__right{ id: 'sell-main__fee' } -
                    %li.clearfix.bold
                      .sell-main__left 販売利益
                      .sell-main__right{ id: 'sell-main__profit' } -
              .sell-main__modal{ role: 'dialog', abindex: '-1' }
                .sell-main__modal-inner
              .sell-main__content.sell-main__btn-box
                
                = f.submit '出品する', class: 'sell-main__btn-default sell-main__btn-red'
                = link_to root_path, class: 'sell-main__btn-default sell-main__btn-gray' do
                  もどる

  .signup-footer
    %nav
      %ul.clearfix
        %li
          = link_to root_path do
            プライバシーポリシー
        %li
          = link_to root_path do
            メルカリ利用規約
        %li
          = link_to root_path do
            特定商取引に関する表記
    = link_to root_path, class: 'signup-footer__logo' do
      = image_tag 'fmarket_logo_white.svg', alt: 'mercari', height: '65', width: '80'
    %p
      %small
        © 2019 Mercari   
          

app/views/items/show.html.haml
= render 'shared/header2'
.breadcrumb
- breadcrumb :detail
= render "shared/breadcrumb"
.item__details
 %h2.item-name.bold
  = @item.name
 .item__details__main-content
  .item__details__main-content-boxes
   .item__details__main-content-boxes__subject.back-silver
    .sold-item-big
     .sold-item--text-big
      = image_tag @item.item_images.first.image, alt: @item.name, size: '300x300'
    .photos
     .photos--small
      -# - @item.item_images.each do |image|
       %img.sub{src: image.image, size: '50x50'}/

   %table.item-detail-table
    %tr
     %th.back-silver 出品者
     %td
      = link_to root_path do
       = @user.nickname
      .user-rating
       .item-user-ratings
       %i.fas.fa-laugh
        %span 100
       .item-user-ratings
       %i.fas.fa-meh
       %span 0
       .item-user-ratings
       %i.fas.fa-frown
       %span 0
    %tr
     %th.back-silver カテゴリー
     %td
      .item-detail-table-sub-category
      %i.fa.fa-chevron-right.items-link_to
      = link_to "ジャケット/アウター", class: "items-link_to" do
       = link_to @category.name
      -# .item-detail-table-sub-sub-category
      -# %i.fa.fa-chevron-right.items-link_to
      -# = link_to "ダウンジャケット", class: "items-link_to" do
      -#  = @item.middle_category
    %tr
     %th.back-silver ブランド
     %td
      -# = link_to @item.brand.name, class: "items-link_to"サーバーサイド未完成のためコメントアウト
      CK
    %tr
     %th.back-silver 商品のサイズ
     %td
      M
    %tr
     %th.back-silver 商品の状態
     %td
      = @condition.value
    %tr
     %th.back-silver 配送料の負担
     %td
      = link_to @delivery_charge.value
      -# = @item.postage.burdenサーバーサイド未完成のためコメントアウト
      送料こみ（出品者負担）
    %tr
     %th.back-silver 配送の方法
     %td
      -# = @item.delivery_method.methodサーバーサイド未完成のためコメントアウト
      ゆゆメルカリ便
    %tr
     %th.back-silver 発送元地域
     %td
      = link_to @prefecture.name
    %tr
     %th.back-silver 発送日の目安
     %td
      = link_to @delivery_days.value
 .item-price-box
  %span.item-price.bold 
   = @item.price 
   円
  %span.item-tax (税込)
  %span.item-shipping-fee 送料込み
  -# - if @item.item_state_id == 3サーバーサイド未完成のためコメントアウト
   = link_to "売り切れました", root_path, class: "buy-btn status-gray",method: :get
  -# - elsif user_signed_in? && (@item.user_id != current_user.id) && @item.item_state_id == 1サーバーサイド未完成のためコメントアウト
   = link_to "購入画面へ進む", "/transaction/buy/#{@item.id}", class: "buy-btn, status-red",method: :get
  -# - unless user_signed_in? || @item.item_state_id == 3サーバーサイド未完成のためコメントアウト
   = link_to "購入画面へ進む", user_session_path, class: "buy-btn, status-red", method: :get

 .item-description
  %p.item-description-inner
  -#  = @item.descriptionサーバーサイド未完成のためコメントアウト
.item-edit__box
 .item-edit__box-main
 - if user_signed_in? && (@item.user_id == current_user.id)
  .item-edit__box__price.back-red.font-white
   = link_to "商品の編集", edit_item_path , method: :get
  .item-edit__box__or or
  .item-edit__box__main-contents
   = form_tag("#", method: :post, action: :stop) do
    %span.font-white 出品を停止する
  .item-edit__box__main-contents__button
   %button{type: "submit", class: "submit", id: "openModal"}
    = link_to "この商品を削除する", item_path(@item), method: :delete
 - else
  .item-button__right.items-link_to
   = link_to '購入画面に進む', purchase_index_path(@item.id), class: 'itembuy-price-box', id: 'itembuy-price-box__decoration'
  .item-button-container
   .item-button-container__left
    %button{name: "like", type: "button"}
     %i.far.fa-heart
     %span いいね！
     %span
      -# = @item.likes_countサーバーサイド未完成のためコメントアウト
    %button{name: "report", type: "button"}
     %i.far.fa-flag
     %span 不適切な商品の報告


  .item-edit__box__main-contents__message
  .message-content__box
.next_or_back
 .previous-product.items-link_to
  -# =fa_icon "#"サーバーサイド未完成のためコメントアウト
  = link_to "前の商品へ", "#"
 .next-product.items-link_to
  = link_to "次の商品へ", "#"
  -# = fa_icon "#"サーバーサイド未完成のためコメントアウト

.item-snsbox
 .sns
  .facebook
   %i.fab.fa-facebook-square
  .twitter
   %i.fab.fa-twitter-square
  .pinterest
   %i.fab.fa-pinterest-square
= render 'shared/fakefooter'
= render 'shared/footer'