config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :addresses
  resources :brands
  resources :sizes
  resources :categories
  resources :comments
  resources :sellers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'items#index'
  resources :users, onry: [:index, :show, :edit] do
    collection do
      get 'confirmation'
      get 'credit'
    end
  end
  resources :signup, only: [:index, :create] do
    collection do
      get 'registration'
      get 'sms'
      get 'address'
      get 'creditcard'
      get 'complete'
    end
  end
  resources :items do
    collection do
      post 'purchase'
    end
  end

  resources :card, only: [:new, :show, :create] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase, only: [:index] do
    collection do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.fetch(:brand, {})
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.haml
= form_for(brand) do |f|
  - if brand.errors.any?
    #error_explanation
      %h2
        = pluralize(brand.errors.count, "error")
        prohibited this brand from being saved:
      %ul
        - brand.errors.full_messages.each do |message|
          %li= message
  .actions
    = f.submit

app/views/brands/edit.html.haml
%h1 Editing Brand
= render 'form', brand: @brand
= link_to 'Show', @brand
|
= link_to 'Back', brands_path

app/views/brands/index.html.haml
%p#notice= notice
%h1 Brands
%table
  %thead
    %tr
      %th{:colspan => "3"}
  %tbody
    - @brands.each do |brand|
      %tr
        %td= link_to 'Show', brand
        %td= link_to 'Edit', edit_brand_path(brand)
        %td= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Brand', new_brand_path

app/views/brands/new.html.haml
%h1 New Brand
= render 'form', brand: @brand
= link_to 'Back', brands_path

app/views/brands/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_brand_path(@brand)
|
= link_to 'Back', brands_path